language: node_js

addons:
  sonarcloud:
    organization: "yourtion-github"
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "$TRAVIS_NODE_VERSION";
      if [ "$TRAVIS_NODE_VERSION" = '8' ]; then
        npm run test:cov && sonar-scanner;
      fi
    fi
  - npm run test

cache:
  directories:
    - node_modules

os:
  - osx
  # - windows
  - linux

node_js:
  - 8
  - 9
  - 10
  - 11
