language: node_js

addons:
  sonarcloud:
    organization: "yourtion-github"
script:
  - sonar-scanner

cache:
  directories:
    - node_modules

os:
  - osx
  # - windows
  - linux

node_js:
  - 8
  - 9
  - 10
  - 11
